# Generated by Django 4.0.2 on 2022-02-13 06:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagefitterA4', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageresource',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imageresource',
            name='source',
            field=models.ImageField(upload_to='images', validators=[django.core.validators.FileExtensionValidator(['jpeg', 'jpg'])]),
        ),
    ]
