# Generated by Django 4.0.2 on 2022-02-13 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('imagefitterA4', '0002_imageresource_name_alter_imageresource_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageresource',
            name='user',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
