# Generated by Django 4.0.2 on 2022-02-13 20:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagefitterA4', '0003_imageresource_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageresource',
            name='orientation',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imageresource',
            name='source',
            field=models.ImageField(upload_to='images/', validators=[django.core.validators.FileExtensionValidator(['jpeg', 'jpg'])]),
        ),
    ]
