# Generated by Django 4.0.2 on 2022-02-13 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagefitterA4', '0004_imageresource_orientation_alter_imageresource_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageresource',
            name='orientation',
            field=models.CharField(max_length=20),
        ),
    ]
