# Generated by Django 4.0.2 on 2022-02-17 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagefitterA4', '0006_imageresource_dimensions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageresource',
            name='source',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
